[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "leure-transition-compass-model"
version = "0.1.0"
description = "Leure Transition Compass Model - Speed to Zero"
readme = "README.md"
requires-python = ">=3.12"


dependencies = [
    "amply>=0.1.6",
    "amplpy>=0.13.0",
    "datamatrix>=1.0.16",
    "deepl>=1.28.0",
    "eurostat>=1.1.1",
    "faostat>=1.1.2",
    "interface>=2.11.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.1",
    "plotly>=6.5.2",
    "pycountry>=26.2.16",
    "pyomo>=6.10.0",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "statsmodels>=0.14.0",
    "tqdm>=4.67.3",
]
